apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamehost-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamehost-microservice
  template:
    metadata:
      labels:
        app: gamehost-microservice
    spec:
      containers:
        - name: gamehost-microservice
          image: docker.io/hostservive_v1/hostservice:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-microservice
  template:
    metadata:
      labels:
        app: player-microservice
    spec:
      containers:
        - name: player-microservice
          image: docker.io/clientservive_v1/clientservice:latest
          ports:
            - containerPort: 3000
