apiVersion: v1
kind: Service
metadata:
  name: node-microservice
spec:
  selector:
    app: node-microservice
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: python-microservice
spec:
  selector:
    app: python-microservice
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer
