version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
  client-microservice:
    image: brauliovieira/tutorial-services:latest-client
    ports:
      - "6000:5000"
  host-microservice:
    image: brauliovieira/tutorial-services:latest-host
    ports:
      - "4000:4000"
networks:
  rabbitmq_nodejs:
    driver: bridge
