version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5

  sender-microservice:
    image: brauliovieira/tutorial-services:latest-sender
    ports:
      - "8080:8080"
  receiver-microservice:
    image: brauliovieira/tutorial-services:latest-receiver
    ports:
      - "4000:4000"
